steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: gcr.io/cloud-builders/git
  entrypoint: bash
  args:
    - c
    - |
    - ls
    - git diff
    - git log
    - git branch