steps:
# fetch history
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
# Find the directories added or updated
- name: gcr.io/cloud-builders/git
  entrypoint: bash
  args:
    - "-c"
    - |
        git diff --diff-filter=AT --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | sort | uniq > changed_dirs.txt
        echo "The changed folders are"
        cat changed_dirs.txt
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - "-c"
    - |
        chmod 400 install_py.sh
        ./install_py.sh
        