steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: gcr.io/cloud-builders/git
  entrypoint: bash
  args:
    - "-c"
    - |
        ls
        git diff
        git log
        git branch
        git diff --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | sort | uniq