steps:
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
- name: gcr.io/cloud-builders/git
  entrypoint: bash
  args:
    - "-c"
    - |
        git diff --diff-filter=AT --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | sort | uniq > changed_dirs.txt
        echo "The changed folders are"
        cat changed_dirs.txt