steps:
# fetch history
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow']
# Find the directories added or updated
- name: gcr.io/cloud-builders/git
  entrypoint: bash
  args:
    - "-c"
    - |
        git diff --diff-filter=AM --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | sort | uniq > changed_dirs.txt
        echo "The changed folders are"
        cat changed_dirs.txt
# Install gcloud and Create template for all the changed folders
- name: python:3.8
  entrypoint: bash
  args:
    - "-c"
    - |
        export PYTHONDONTWRITEBYTECODE=1
        chmod +x ./install_gcloud.sh
        bash ./install_gcloud.sh
        gcloud --version
        gcloud config get project
        cat changed_dirs.txt
        chmod +x ./run.sh
        bash ./run.sh
        